### PR TITLE
[WIP] Os upgrade

### PR DESCRIPTION
**Pull request by notartom**

### CODE REVIEW

**Comment by redrun45** [comment]
What version are we looking to upgrade to?  I'm setting up a local environment myself, so I may be able to help troubleshoot the differences.
If I don't hear back, I'll just try this branch against a couple LTS's and see what sticks.  😉

**Comment by notartom** [comment]
Latest Ubuntu LTS is what we would want, so 22.04 at the time of this writing?

Also, I think I allowed scope creep to cloud my actions when I started this. While there will be things that we _must_ do to get LV running on 22.04 and PHP 7, some other things that I started here aren't directly relevant to the OS upgrade, for example the MySQL customization. Sure, we'll get a new version of MariaDB, but our custom configs should still work, even if they might not be relevant anymore.

All that to say - perhaps the best approach is just to try the existing playbooks on 22.04, limiting ourselves to fixing what's broken. Any other aspirational stuff can come after.

**Comment by redrun45** [comment]
Fair enough!  I understand that your time for this is limited, so if you'd like, I'll start another WIP branch with a minimal set of changes cherry-picked from here, and see how far I can take it.

If there's anything else I can do to help you out (categorize tickets on the other repo?), I'm happy to help as far as my "general Linux enthusiast" skill level allows.

**Comment by notartom** [comment]
> Fair enough! I understand that your time for this is limited, so if you'd like, I'll start another WIP branch with a minimal set of changes cherry-picked from here, and see how far I can take it.

Honestly if you can get the playbooks running successfully on latest Ubuntu LTS it would be a massive step forward. Cherry-picking anything from this PR is at best a stretch goal - or put differently: we can clean the playbooks up in a second phase.

> If there's anything else I can do to help you out (categorize tickets on the other repo?), I'm happy to help as far as my "general Linux enthusiast" skill level allows.

So, there are two ways to approach this: what the volunteers need, and what the infrastructure (fancy word that implies more than there actually is, but I don't have another one) needs.

Since I don't actually participate in the audiobook producing part of LV (history tl;dr: I was brought on as a paid sysadmin, then stuck around as a volunteer), I don't have a lot of context as to what the volunteers needed. There are 55 issues in https://github.com/LibriVox/librivox-catalog. I went through a few, and added tags that correspond to the priority in the description (5,4 = low, 3 = medium, 2, 1 = high). There are a bunch with missing priorities, and a bunch that I didn't go through yet. We should finish assigning priority labels, and then work on the highest priority ones.

On the infra side, I want to update to latest Ubuntu LTS, get everything working with PHP 7, and that will allow us to move to updated versions of WordPress, etc.

**Comment by vbock** [comment]
I'm still on this list because I was the project manager on that paid
engagement years ago, but as a veteran of getting stuff working under a new
OS, I STRONGLY support concentrating on that, first.  The weirdest stuff
stops working with an OS or database upgrade.   The syntax for an oft-used
query changes, (documented in some obscure spot, or not at all) and
suddenly it doesn't work.  We once had an upgrade that changed the default
email server, and didn't realize we had to add our preferred one back.
That was big fun!


Valerie Bock
***@***.***

**Comment by notartom** [comment]
Will reopen a new and improved one.

**Pull request closed without merging**
