### PR TITLE
Improve localdev doc and fold it into the main README

### PR DESCRIPTION
**Pull request by notartom**
Closes issue #11

### CODE REVIEW

**Comment by notartom** [comment]
@redrun45 your review/feedback would be appreciated :) The guide itself is hopefully improvement, but I've also invested some elbow grease into localdev itself, and even into some CI to dpeloy it on every PR.

**Comment by redrun45** [comment]
Yes, it certainly looks like an improvement! I see several of the issues I ran into are addressed, and that work on the localdev role makes for a much shorter list of manual steps.

I particularly like the new caveats/disclaimers section. A succinct statement of what I should expect from a successful deployment.

Only one step I'd add so far: adding the localdev target IP to inventory.yaml before the ansible-playbook command.

I'll give this process a go within the next few days, and get back to you if I have any other suggestions.

**Comment by notartom** [comment]
>I particularly like the new caveats/disclaimers section. A succinct statement of what I should expect from a successful deployment.

👍

> Only one step I'd add so far: adding the localdev target IP to inventory.yaml before the ansible-playbook command.

Good point, I've added that in the most recent version.

**Comment by notartom** [comment]
On the basis that something is better than nothing, I'm going to merge this. If there are further comments/suggestions/feedback, please open new issues :)

**Pull request merged**
